name: Deploy Landing Page - DEV
on:
  push:
    branches:
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      env: development
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
        - uses: actions/checkout@v1
        
        - name: Deploy 🚀
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: ./
            bucket: ${{ secrets.S3_BUCKET_DEV }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
            invalidation: / *
  